on:
  workflow_call:
    inputs:
      repository-name:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  autolabel:
    runs-on: ubuntu-latest
    if: ${{ github.repository == inputs.repository-name }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Autolabel Pull Request
        uses: release-drafter/release-drafter/autolabeler@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7.10.0
        with:
          token: ${{ secrets.token }}
