on:
  workflow_call:
    inputs:
      repository-name:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  autolabel:
    runs-on: ubuntu-latest
    if: ${{ github.repository == inputs.repository-name }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Autolabel Pull Request
        uses: release-drafter/release-drafter/autolabeler@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        with:
          token: ${{ secrets.token }}
